### ISSUE TITLE
Questions: Simplified wiring

### ISSUE THREAD

**Issue by kratz00** [RobPo/Paperino#9]
I have two questions regarding the optional simplified wiring.

1. What are the pros and cons of that approach?
Obviously one pro is that you will have two GPIO pins for other purposes. So maybe the real question is:
Are there any downsides using the simplified wiring?

2. It is currently not documented in the [Hookup Guide](https://robpo.github.io/Paperino/#1-hardware-hookup). Which probably would also be a great place to answer my first question.

**Comment by RobPo** [comment]
Yes there is a disadvantage for the simplified wiring: The communication process with the driver IC is slower, because rather than sensing the "busy" line and continuing with the communication as soon as the busy line is not active anymore, there are some fix waiting delays set for the busy periods. So the image updates are slightly slower and less responsive... Its also likely to be more failure-prone to rely on the timing alone. So generally I would rather recommend to use the standard setup.
I will add a note in the hook-up guide.
